### Get cart for user
GET http://localhost:3004/api/cart/test@test.com

### Add to cart
POST http://localhost:3004/api/cart/add
content-type: application/json

{ 
  "email":"test@test.com",
  "shoe_id":1
}

### Remove from cart
POST http://localhost:3004/api/cart/remove
content-type: application/json

{ 
  "email":"test@test.com",
  "shoe_id":10
}
### Delete Item From Cart
POST http://localhost:3004/api/cart/delete
content-type: application/json

{ 
  "shoe_id":10
}
### Sold Shoe
POST http://localhost:3004/api/cart/sold

### Cart payment
POST http://localhost:3004/api/cart/payment
Content-Type: application/json

{
  "email":"test@test.com",
  "payment":233900
}