GET http://localhost:3004/api/shoes

###
GET http://localhost:3004/api/shoes/8

###
GET http://localhost:3004/api/shoes/12

###
GET http://localhost:3004/api/shoes/brand/Naked Wolfe

###
GET http://localhost:3004/api/shoes/size/7

###
GET http://localhost:3004/api/shoes/color/Brown
###
GET http://localhost:3004/api/shoes/brand/Moschino/size/11

###
GET http://localhost:3004/api/shoes/brand/Moschino/color/Brown

###
GET http://localhost:3004/api/shoes/size/9/color/Black

###
GET http://localhost:3004/api/shoes/brand/Moschino/size/7/color/Black

###
POST http://localhost:3004/api/shoes
Content-Type: application/json

{
  "brand":"ANTONY MORATO",
  "name":"ANTONY MORATO MAN FOOTWEAR MMFW01577-LE300001-1000",
  "size":"8",
  "color":"White",
  "quantity":"5",
  "image_url":"https://www.hydraulicsstores.co.za/wp-content/uploads/2024/02/MMFW01577-LE300001-1000_01.jpg",
  "new_price": "2375"
}

###
POST http://localhost:3004/api/shoes/sold/24
